version: '2.12.2'
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - 3002:3002 
    networks:
      - travel-hub-net
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 3000:3000
    networks:
      - travel-hub-net
    depends_on:
      - api

  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - 27018:27017
    networks:
      - travel-hub-net
    volumes:
      - mongodb-data:/data/db
      
networks:
  travel-hub-net:
    driver: bridge

volumes:
  mongodb-data:
    driver: local