import NavBar from "./common/NavBar"
import Footer from "./common/Footer"
import Hero from "./home/Hero"
import DestinationCard from "./destinations/DestinationCard"
import NotFound from "./NotFound"
import FormContainer from "./forms/FormContainer"
import Input from "./forms/Input"
import GeneralDetails from "./destinations/GeneralDetails"
import Itenary from "./destinations/Itenary"
import Galleries from "./destinations/Galleries"
import Booking from "./destinations/Booking"
import UpdateInfos from "./profile/UpdateInfos"
import Bookings from "./profile/Bookings"
import Header from "./admin/Header"
import Sidebar from "./admin/Sidebar"
import Wrapper from "./admin/Wrapper"
import Alert from "./forms/Alert"
import RequireAuth from "./auth/RequireAuth"
import Loading from "./common/Loading"

export { NavBar, Footer, Hero, DestinationCard, NotFound, FormContainer, Input, GeneralDetails, Itenary, Galleries, Booking, UpdateInfos, Bookings, Header, Sidebar, Wrapper, Alert, RequireAuth, Loading }
