const inputs = [
    {
        type: "email",
        id: "email",
        name: "email",
        placeholder: "jhondoe@gmail.com",
        label: "Email",
        class: "block p-3 w-full",
        err: false,
        errMsg: "",
        testid: "emailInput",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
    {
        type: "password",
        id: "password",
        name: "password",
        placeholder: "************",
        label: "Password",
        class: "block p-3 w-full",
        err: false,
        errMsg: "",
        testid: "pwdInput",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
];
const inputs1 = [
    {
        type: "text",
        id: "username",
        name: "username",
        placeholder: "JhonDoe",
        label: "Username",
        class: "block p-3 w-full",
        err: false,
        errMsg: "",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
    {
        type: "email",
        id: "email",
        name: "email",
        placeholder: "jhondoe@gmail.com",
        label: "Email",
        class: "block p-3 w-full",
        err: false,
        errMsg: "",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
    {
        type: "password",
        id: "password",
        name: "password",
        placeholder: "************",
        label: "Password",
        class: "block p-3 w-full",
        err: false,
        errMsg: "",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
    {
        type: "password",
        id: "repeatpassword",
        name: "password",
        placeholder: "************",
        label: "Repeat Password",
        class: "block p-3 w-full",
        err: false,
        errMsg: "",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
];
const inputs2 = [
    {
        type: "email",
        id: "email",
        name: "email",
        placeholder: "jhondoe@gmail.com",
        label: "Email",
        class: "block p-3 w-full",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
    {
        type: "submit",
        id: "submit",
        name: "submit",
        value: "Submit",
        class: "block my-5 text-dark font-medium cursor-pointer w-full",
        style: {
            backgroundColor: "#41CD7D",
            outline: "none",
            padding: "10px",
            borderRadius: "10px",
        },
    },
];
const inputs3 = [
    {
        type: "password",
        id: "newpassword",
        name: "newpassword",
        placeholder: "***********",
        label: "New Password",
        class: "block p-3 w-full",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
    {
        type: "password",
        id: "repeatpassword",
        name: "repeatpassword",
        placeholder: "***********",
        label: "Repeat Password",
        class: "block p-3 w-full",
        style: {
            backgroundColor: "#303246",
            outline: "none",
            color: "white",
            padding: "10px",
            borderRadius: "10px",
        },
    },
    {
        type: "submit",
        id: "submit",
        name: "submit",
        value: "Submit",
        class: "block my-5 text-dark font-medium cursor-pointer w-full",
        style: {
            backgroundColor: "#41CD7D",
            outline: "none",
            padding: "10px",
            borderRadius: "10px",
        },
    },
];

export { inputs, inputs1, inputs2, inputs3 };
